// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmhbaesggjrqcsgkziic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtaGJhZXNnZ2pycWNzZ2t6aWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzY2MzgsImV4cCI6MjA2ODA1MjYzOH0.Vv9wpnpmJGdvgoJVgbvjIwnzKmjlZCYJw6FTkXov5og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});